services:
  naritcm-cleanroom-api:
    build: .
    container_name: naritcm-cleanroom-api
    restart: unless-stopped
    stop_grace_period: 10s

    ports:
      - "8000:8000"

    privileged: false
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/gpiochip0:/dev/gpiochip0"

    environment:
      STATIC_DIR: "static"
      SERIAL_PORT: "/dev/ttyACM0"
      BAUDRATE: "9600"
      PARITY: "N"
      BYTESIZE: "8"
      STOPBITS: "1"
      TIMEOUT_S: "1.0"
      READ_TABLE: "holding"
      REG_START: "0"
      REG_COUNT: "2"
      TEMP_INDEX: "1"
      HUMI_INDEX: "0"
      SCALE_DIV: "10"
      ROOM1: "1"
      OUTDOOR_ID: "2"
      POLL_MS: "1000"

    networks:
      - cleanroom-net

  sensor-writer:
    build: ./writer
    container_name: sensor-writer
    restart: unless-stopped

    environment:
      SENSOR_API_URL: "http://naritcm-cleanroom-api:8000/api/sensor/1"
      POLL_SEC: "1.0"
      HTTP_TIMEOUT_SEC: "2.5"
      INFLUX_URL:    "http://influxdb:8086"
      INFLUX_ORG:    "Narit"
      INFLUX_BUCKET: "Cleanroom"
      MEASUREMENT:   "room1"
      INFLUX_TOKEN:  "kTRPZoj7DxBnKY4xDy5kJty6KZhv4BXg5W9JiUGdh9kdaPQr5RF9lic0TYx_3XucOqNHnGlydlTQwFiwuPS-6Q=="

    depends_on:
      - naritcm-cleanroom-api
      - influxdb

    networks:
      - cleanroom-net

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped

    ports:
      - "8086:8086"

    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

    environment:
      DOCKER_INFLUXDB_INIT_MODE:        "setup"
      DOCKER_INFLUXDB_INIT_USERNAME:    "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD:    "12345678"   # เปลี่ยนได้
      DOCKER_INFLUXDB_INIT_ORG:         "Narit"
      DOCKER_INFLUXDB_INIT_BUCKET:      "Cleanroom"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "kTRPZoj7DxBnKY4xDy5kJty6KZhv4BXg5W9JiUGdh9kdaPQr5RF9lic0TYx_3XucOqNHnGlydlTQwFiwuPS-6Q=="

    networks:
      - cleanroom-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER:     "admin"
      GF_SECURITY_ADMIN_PASSWORD: "12345678"   # เปลี่ยนได้
      GF_DATAPROXY_TIMEOUT:            "300"
      GF_DATAPROXY_DIAL_TIMEOUT:       "30"
      GF_DATAPROXY_KEEP_ALIVE_SECONDS: "300"
      GF_AUTH_ANONYMOUS_ENABLED:       "true"
      GF_AUTH_ANONYMOUS_ORG_NAME:      "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE:      "Viewer"

    depends_on:
      - influxdb

    networks:
      - cleanroom-net

volumes:
  influxdb-data:
  influxdb-config:
  grafana-data:

networks:
  cleanroom-net:
    driver: bridge